bracketSpacing: true
bracketSameLine: false
singleQuote: false
trailingComma: "all"
semi: true
useTabs: false
tabWidth: 4
endOfLine: lf

# @trivago/prettier-plugin-sort-imports
importOrder: ["<THIRD_PARTY_MODULES>", "@/(.*)$", "^[./](.*)$"]
importOrderSeparation: true
importOrderSortSpecifiers: true

overrides:
  - files: ["*.json", "*.yaml", "*.yml"]
    options:
      tabWidth: 2
