name: api

on:
  pull_request:
    paths-ignore:
      - "**.md"
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.5
          run_install: false

      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build `api` workspace
        run: pnpm api build
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.5
          run_install: false

      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Run unit-test
        run: pnpm api test

      - name: Run integration-test
        run: pnpm api test:e2e

      - name: Generate coverage
        run: pnpm api test:cov
